[phases.setup]
nixPkgs = ['php81', 'php81Extensions.mysqli', 'php81Extensions.pdo', 'php81Extensions.pdo_mysql']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader']

[phases.build]
cmds = ['php database_setup.php']

[start]
cmd = 'php -S 0.0.0.0:$PORT -t .'
