# railway.toml - Railway deployment configuration

[[services]]
name = "evaluation-app"
source = "."

[services.evaluation-app.build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[services.evaluation-app.deploy]
startCommand = "start.sh"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10