[build]
builder = "dockerfile"

[deploy]
startCommand = "/usr/local/bin/start.sh"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
# These will be automatically provided by Railway's MySQL service
# MYSQLHOST will be set by Railway
# MYSQLPORT will be set by Railway  
# MYSQLDATABASE will be set by Railway
# MYSQLUSER will be set by Railway
# MYSQLPASSWORD will be set by Railway
